package com.onlinebanking.models;

// Generated using hibernate tools

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.onlinebanking.helpers.ValidationHelper;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "pitchforkbank")
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3777066039079460075L;
	private int accountNum;
	private User user;
	private String accountType;
	private double amount;

	public Account() {
		this.accountNum = ValidationHelper.generateRandomNumber(1000, 9999);
	}

	public Account(int accountNum, User user, String accountType, double amount) {
		this.accountNum = accountNum;
		this.user = user;
		this.accountType = accountType;
		this.amount = amount;
	}

	@Id
	@Column(name = "accountNum", unique = true, nullable = false)
	public int getAccountNum() {
		return this.accountNum;
	}

	public void setAccountNum(int accountNum) {
		this.accountNum = accountNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "accountType", nullable = false, length = 45)
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "amount", nullable = false)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}
}
