package com.onlinebanking.models;

// Generated Oct 19, 2014 4:55:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Requests generated by hbm2java
 */
@Entity
@Table(name = "requests", catalog = "pitchforkbank")
public class Requests implements java.io.Serializable {

	private static final long serialVersionUID = -5186186264356733568L;
	private String requestId;
	private String fromUser;
	private String toUser;
	private String type;
	private String status;

	public Requests() {
		this.requestId = UUID.randomUUID().toString();
	}

	public Requests(String requestId,  String fromUser, String toUser, String type, String status) {
		this.requestId = requestId;
		this.fromUser = fromUser;
		this.toUser = toUser;
		this.status = status;
		this.type = type;
	}

	@Id
	@Column(name = "requestId", unique = true, nullable = false, length = 64)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Column(name = "fromUserId", nullable = false, length = 64)
	public String getFromUser() {
		return this.fromUser;
	}

	public void setFromUser(String user) {
		this.fromUser = user;
	}
	
	@Column(name = "toUserId", nullable = false, length = 64)
	public String getToUser() {
		return this.toUser;
	}

	public void setToUser(String user) {
		this.toUser = user;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
