package com.onlinebanking.models;

// Generated Oct 19, 2014 4:55:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Userotp generated by hbm2java
 */
@Entity
@Table(name = "userotp", catalog = "pitchforkbank", uniqueConstraints = @UniqueConstraint(columnNames = "oneTimePassword"))
public class Userotp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2003592439873576591L;
	private String userId;
	private User user;
	private String oneTimePassword;

	public Userotp() {
	}

	public Userotp(User user, String oneTimePassword) {
		this.user = user;
		this.oneTimePassword = oneTimePassword;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "userId", unique = true, nullable = false, length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "oneTimePassword", unique = true, nullable = false, length = 45)
	public String getOneTimePassword() {
		return this.oneTimePassword;
	}

	public void setOneTimePassword(String oneTimePassword) {
		this.oneTimePassword = oneTimePassword;
	}

}
